import process from "node:process";
import { fileURLToPath, URL } from "node:url";
import { tanstackRouter } from "@tanstack/router-plugin/vite";
import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";

const host = process.env["TAURI_DEV_HOST"];

export default defineConfig({
  plugins: [
    tanstackRouter({
      target: "react",
      routesDirectory: "./src/route",
      generatedRouteTree: "./src/route-tree.gen.ts",
      routeFileIgnorePattern: "^business$",
      routeTreeFileHeader: ["// Generated by TanStack Router. Do not edit."],
      quoteStyle: "double",
      semicolons: true,
      autoCodeSplitting: true,
    }),
    react(),
  ],
  resolve: { alias: { "@": fileURLToPath(new URL("./src", import.meta.url)) } },
  clearScreen: false,
  build: {
    target: ["chrome111", "safari16.4"],
    cssTarget: ["chrome111", "safari16.4"],
  },
  server: {
    port: 1420,
    strictPort: true,
    host: host ?? false,
    hmr: host ? { protocol: "ws", host, port: 1421 } : false,
    watch: { ignored: ["**/src-tauri/**"] },
  },
});
