import { resolve } from "node:path";
import { getConfig } from "@tanstack/router-generator";
import type { Config } from "@tanstack/router-generator";

export function routeConfig(root: string): Config {
  return getConfig(
    {
      target: "react",
      routesDirectory: "./src/route",
      generatedRouteTree: "./src/route-tree.gen.ts",
      tmpDir: resolve(root, ".tanstack/tmp"),
      routeFileIgnorePattern: "^business$",
      routeTreeFileHeader: ["// Generated by TanStack Router. Do not edit."],
      quoteStyle: "double",
      semicolons: true,
    },
    root,
  );
}
