// Generated by TanStack Router. Do not edit.

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./route/__root";
import { Route as IndexRouteImport } from "./route/index";
import { Route as HomeRouteRouteImport } from "./route/home/route";
import { Route as ComicComicIdRouteRouteImport } from "./route/comic/$comicId/route";
import { Route as HomeIndexRouteImport } from "./route/home/index";
import { Route as ComicComicIdIndexRouteImport } from "./route/comic/$comicId/index";
import { Route as ComicComicIdTranslatorRouteImport } from "./route/comic/$comicId/translator";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const HomeRouteRoute = HomeRouteRouteImport.update({
  id: "/home",
  path: "/home",
  getParentRoute: () => rootRouteImport,
} as any);
const ComicComicIdRouteRoute = ComicComicIdRouteRouteImport.update({
  id: "/comic/$comicId",
  path: "/comic/$comicId",
  getParentRoute: () => rootRouteImport,
} as any);
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => HomeRouteRoute,
} as any);
const ComicComicIdIndexRoute = ComicComicIdIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ComicComicIdRouteRoute,
} as any);
const ComicComicIdTranslatorRoute = ComicComicIdTranslatorRouteImport.update({
  id: "/translator",
  path: "/translator",
  getParentRoute: () => ComicComicIdRouteRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/home": typeof HomeRouteRouteWithChildren;
  "/comic/$comicId": typeof ComicComicIdRouteRouteWithChildren;
  "/home/": typeof HomeIndexRoute;
  "/comic/$comicId/translator": typeof ComicComicIdTranslatorRoute;
  "/comic/$comicId/": typeof ComicComicIdIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/home": typeof HomeIndexRoute;
  "/comic/$comicId/translator": typeof ComicComicIdTranslatorRoute;
  "/comic/$comicId": typeof ComicComicIdIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/home": typeof HomeRouteRouteWithChildren;
  "/comic/$comicId": typeof ComicComicIdRouteRouteWithChildren;
  "/home/": typeof HomeIndexRoute;
  "/comic/$comicId/translator": typeof ComicComicIdTranslatorRoute;
  "/comic/$comicId/": typeof ComicComicIdIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/home"
    | "/comic/$comicId"
    | "/home/"
    | "/comic/$comicId/translator"
    | "/comic/$comicId/";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/home" | "/comic/$comicId/translator" | "/comic/$comicId";
  id:
    | "__root__"
    | "/"
    | "/home"
    | "/comic/$comicId"
    | "/home/"
    | "/comic/$comicId/translator"
    | "/comic/$comicId/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  HomeRouteRoute: typeof HomeRouteRouteWithChildren;
  ComicComicIdRouteRoute: typeof ComicComicIdRouteRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/home": {
      id: "/home";
      path: "/home";
      fullPath: "/home";
      preLoaderRoute: typeof HomeRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/comic/$comicId": {
      id: "/comic/$comicId";
      path: "/comic/$comicId";
      fullPath: "/comic/$comicId";
      preLoaderRoute: typeof ComicComicIdRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/home/": {
      id: "/home/";
      path: "/";
      fullPath: "/home/";
      preLoaderRoute: typeof HomeIndexRouteImport;
      parentRoute: typeof HomeRouteRoute;
    };
    "/comic/$comicId/": {
      id: "/comic/$comicId/";
      path: "/";
      fullPath: "/comic/$comicId/";
      preLoaderRoute: typeof ComicComicIdIndexRouteImport;
      parentRoute: typeof ComicComicIdRouteRoute;
    };
    "/comic/$comicId/translator": {
      id: "/comic/$comicId/translator";
      path: "/translator";
      fullPath: "/comic/$comicId/translator";
      preLoaderRoute: typeof ComicComicIdTranslatorRouteImport;
      parentRoute: typeof ComicComicIdRouteRoute;
    };
  }
}

interface HomeRouteRouteChildren {
  HomeIndexRoute: typeof HomeIndexRoute;
}

const HomeRouteRouteChildren: HomeRouteRouteChildren = {
  HomeIndexRoute: HomeIndexRoute,
};

const HomeRouteRouteWithChildren = HomeRouteRoute._addFileChildren(
  HomeRouteRouteChildren,
);

interface ComicComicIdRouteRouteChildren {
  ComicComicIdTranslatorRoute: typeof ComicComicIdTranslatorRoute;
  ComicComicIdIndexRoute: typeof ComicComicIdIndexRoute;
}

const ComicComicIdRouteRouteChildren: ComicComicIdRouteRouteChildren = {
  ComicComicIdTranslatorRoute: ComicComicIdTranslatorRoute,
  ComicComicIdIndexRoute: ComicComicIdIndexRoute,
};

const ComicComicIdRouteRouteWithChildren =
  ComicComicIdRouteRoute._addFileChildren(ComicComicIdRouteRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRouteRoute: HomeRouteRouteWithChildren,
  ComicComicIdRouteRoute: ComicComicIdRouteRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
